### ISSUE TITLE
UnboundLocalError when there is no hit in blast result

### ISSUE THREAD

**Issue by posativ** [sonwell/biotools#3]
With this blast result

```
BLASTN 2.2.25+


Reference: Zheng Zhang, Scott Schwartz, Lukas Wagner, and Webb
Miller (2000), "A greedy algorithm for aligning DNA sequences", J
Comput Biol 2000; 7(1-2):203-14.



Database: musa_pseudochromosome_RM.fa
           12 sequences; 472,960,417 total letters



Query= OsMADS57_AGL17
Length=687


***** No hits found *****



Lambda     K      H
    1.33    0.621     1.12 

Gapped
Lambda     K      H
    1.28    0.460    0.850 

Effective search space used: 311680693379


  Database: musa_pseudochromosome_RM.fa
    Posted date:  Aug 6, 2012  1:09 PM
  Number of letters in database: 472,960,417
  Number of sequences in database:  12



Matrix: blastn matrix 1 -2
Gap Penalties: Existence: 0, Extension: 2.5
```

I get the following:

```
Traceback (most recent call last):  File "untitled.py", line 30, in <module>
    for i, result in enumerate(blast(gene, dbpath)):
  File "/Users/ich/dev/musa_acuminata/lib/python2.7/site-packages/biotools/BLAST.py", line 283, in __iter__
    yield ra(subheaders)
UnboundLocalError: local variable 'subheaders' referenced before assignment
```

**Comment by sonwell** [comment]
This should be fixed.

**Comment by posativ** [comment]
Wow, that was fast. Thank you!
